name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "*/3 * * * *"
jobs:
  testings:
    runs-on: "self-hosted"
    steps:
    - name: Run a one-line script
      run: |
            echo Hello, world!
            uname -a
            ip addr